### ISSUE TITLE
Set CPU core count

### ISSUE THREAD

**Issue by rhssk** [paliarush/vagrant-magento#108]
By default a fresh installation always ends up having just 1 CPU core. It is possible to change that in Vagrant file by adding
`config.vm.provider "virtualbox" do |v|
  v.cpus = X
end`

Maybe it could be possible to automatize this with something like this?
https://gist.github.com/WIZARDISHUNGRY/2660808

**Comment by paliarush** [comment]
@rhssk Have you tried to set 2 or more CPUs for this box? Does it give any performance improvement?
I can make it configurable via `config.yaml` (the same way it is done for RAM). I'm not sure if it makes sense to increase the number of CPUs automatically because you can have multiple boxes running at the same time and as far as I understand, each of them will reserve specified number of CPUs

**Comment by rhssk** [comment]
For me the difference between 1 and 2 cores is very noticeable, especially after clearing cache and reloading site.

**Comment by FinBoWa** [comment]
I'd suggest against it to be automatic if you referer on this: 

https://github.com/geerlingguy/drupal-vm/issues/855

But making it default to 1 and allow to it be changed easily it would be something that is good to add as it would be easier give more cpus if you don't mind the performance hit.
