### ISSUE TITLE
Create an AWS AMI with a compatible environment

### ISSUE THREAD

**Issue by degaray** [paliarush/vagrant-magento#110]
I spent some days trying to get magento2 running on Docker but after realizing it is not compatible with NFS, then it really delivers a very poor performance. Could you create a similar environment we could use on AWS, Digital Ocean or both for production?

**Comment by paliarush** [comment]
The main purpose of this project is to give tools to make daily Magento2 development more productive. And here I mainly share what is useful for me personally. For example there are no tools for frontend developers, that's because I don't do frontend development and don't know how to make it more convenient for others. If someone decides to contribute something for frontend development, I would  be glad to accept it though. The same is true for integration with production environment.

There is development of docker dev box going on by Magento core team, and I believe it should have features you describe: check it out [here](https://gist.github.com/piotrekkaminski/2221b14b2cb19d93ad0025c19345ff96).
