### ISSUE TITLE
'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by s2010** [paliarush/vagrant-magento#127]
how to change the loaded configuration file used by the php cli.
my web server uses /etc/php/7.0/apache2/php.ini
my php cli uses /usr/local/php5/lib/php.ini
my php cli version PHP 7.0.15 (cli)

**Comment by paliarush** [comment]
Use `use_php7` option in `<vagrant_project>etc/config.yaml` to choose between PHP 5 or PHP 7. Then it should be switched automatically after `vagrant reload` on the guest Ubuntu machine. This should change current version for both, web server and CLI.

Also not sure why you've got PHP 7.0.15, the version I have is `PHP 7.0.7-4+deb.sury.org~trusty+1`

**Comment by medmek** [comment]
seems like when deprecating this option (for the new php_version), this issue came up again,
when I wasn't sure about this, i chose changing [scripts\guest\m-reinstall] `setupOption[db_host]='localhost'` to `127.0.0.1 `as suggested in https://magento.stackexchange.com/a/148613/51034
but not sure either if this isn't breaking something else

**Comment by paliarush** [comment]
@medmek if your Magento instance still works and can access DB, then changing `db_host` should be fine.
