### ISSUE TITLE
Survey: How do you use this project?

### ISSUE THREAD

**Issue by paliarush** [paliarush/vagrant-magento#141]
Hi guys, 

I am Magento core developer and may not know all the issues you may face as a community developer. To improve current project, I am trying to collect more information about the use cases community developers have in their daily work.

I would appreciate If you could **share your typical project structure and how you use this vagrant project**. 

Maybe there are some missing features, which could make your life easier.

Thanks
Alex

**Comment by paliarush** [comment]
@jasonheecs @CellFishy @nfourteen @wpoortman @sunel @MurKit @WillPS1989 @andertun @GerardKetuma @jwineman @dimstar @s2010 @henryhardy @tmos @nicolaspernot @samuelecarpene @PivitParkour94 @crantron @TapaniAla @degaray @kaynenh @rhssk @dazuaz @jasonalvis @apothegm @jatasya @createadrln @nobuttsalex @hvstudio @LCIJJ @crantron @Szaamaan @refaelgold @willboudle @Jrb1x @dlehren @CNSam @riconeitzel @aaronallen8455 @ClaudiuCreanga since you reported issues for this project some time ago, I assume you used it and would appreciate if you could share your experience, thanks.

**Comment by degaray** [comment]
I ended up using another one since I have nginx installed in my production site.

**Comment by degaray** [comment]
I ended up using another one since I have nginx installed in my production site.

**Comment by dazuaz** [comment]
Hello, I ended setting up valet, which was a lot faster for me in Mac

**Comment by Jrb1x** [comment]
I'm also using Valet. It's insanely fast. No VM's. Just a Docker container for Redis and RabbitMQ.

**Comment by jwineman** [comment]
I maintain Cloudflare's magento plugin.  We use vagrant internally for our development environment so I wanted a vagrant setup for magento as well to ease new developer's ability to get up to speed.  

Pros:

- Easy to get up and running
- Easy to reset to known state

Cons:

- I don't like the bash scripts that wrap `bin/magento` and `composer`.  They occasionally swallow errors and when something breaks I'm not sure if the environment (bash script) is broken or if my code is the root cause.  I would rather `vagrant ssh` and use the box but I assume the bash scripts exist for a reason.
- Switching between magento versions isn't straight forward.  Its been a while since I did it but I remember being very confused trying to reproduce a bug on a different version of Magento.  It took me half a day to get the vagrant box on a different version.

Overall I LOVE this project and it has saved me a lot of time - keep up the great work and thanks for everything you've done so far!

**Comment by andertun** [comment]
I ended up going in another direction (Shopify). Magento 2 and the different environment setups I tried was too time consuming to get to work properly for the webshop I am building.

**Comment by rhssk** [comment]
Wrote bash script to create / clean-up projects directly (create nginx configs from templates, MySQL users / databases etc.) and have been using that instead of Vagrant since the projects were significantly slower to work on than when running them without any virtualization.

**Comment by nobuttsalex** [comment]
Staying away from any virtual environments from now on. The file syncing between the host machine and virtual box/docker is always painfully slow.

**Comment by WillPS1989** [comment]
I couldn't get it to work as I needed to - cloning the git repository worked but for whatever reason the Composer method wouldn't. I tried Magestead but had problems with that too. In the end I just used Scotchbox.

An all-in-one solution like this is still desired by me.

**Comment by samuelecarpene** [comment]
I'm very intrested in this solution. Under Windows 10 is very difficult to use vagrant.

**Comment by nfourteen** [comment]
I'm with @jwineman. His pros and cons mirror my own. I also really like how easy it is to install and uninstall sample data.

I have been looking into Valet as a means to speed things up. NFS is really slow and I quit using `grunt watch` because it was taking 15-20 seconds for it to pick up the file changes. I've upped the box to use 4GB, but I'm still getting pretty bad page load times (kind of understandable in developer mode), which I think is still an NFS problem.

Overall, this is a great project and saved me a lot of set up time. If I ever work with the enterprise edition of Magento, I could see where this box would be invaluable to setting up different caching layers and services. Thank you for putting this together and making it available to the community!

**Comment by jasonheecs** [comment]
Hi. I've pretty much moved to use Docker for my Magento 2 projects as I've found it to be much faster.

I still think this is a great project though, and it's nice to have choices :)

**Comment by paliarush** [comment]
Thanks everyone for the feedback!
