### ISSUE TITLE
Clean up legacy code 

### ISSUE THREAD

**Issue by paliarush** [paliarush/vagrant-magento#151]
Some scripts were added for backward compatibility and smooth upgrades more than a year ago.
Now they just increase complexity and do give any value.

**Comment by ghost** [comment]
I am running windows 8.1 and tried to run your script, but failed.  Should I upgrade to Windows 10?
I desperately need your script running because I need Varnish running on Windows environment.  And your scripts is the only hope I have now. Should I run 'Vagrant up' before executing 'init_project.sh'?  I got two VM running if I did 'Vagrant up' before 'init_project.sh'.   if I run 'Vagrant up' from command prompt as administrator, then there will be no VM, but still has many red line errors.  Please advise me.  Your earliest attention will be much appreciated.

**Comment by paliarush** [comment]
Hi @ghost, I tested this project on Windows 10 some time ago and it worked.
Please do not run 'vagrant up' before 'init_project.sh'. Make sure to use git bash 2.7+ instead of native windows CLI because all scripts are written in bash.

I will try to find Windows machine and test it again and will let you know the result.

Sorry for the delayed response. Thanks
