### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by gilles6** [paliarush/vagrant-magento#159]
How to fix this issue ?

MacBook-Pro-de-Max:vagrant-magento max$ bash init_project.sh
[2017-10-19 18:07:33] Checking requirements [/Users/max/magento/vagrant-magento/scripts/host/check_requirements.sh]
[2017-10-19 18:07:33] Installing missing vagrant plugins [init_project.sh]
[2017-10-19 18:07:34] Generating random IP address, and host name to prevent collisions (if no custom values specified) [init_project.sh]
[2017-10-19 18:07:34] Installing Magento dependencies via Composer [init_project.sh]
[2017-10-19 18:07:34] Executing composer command [/Users/max/magento/vagrant-magento/scripts/host/composer.sh]
[2017-10-19 18:07:34] >  Checking requirements [/Users/max/magento/vagrant-magento/scripts/host/check_requirements.sh]
[2017-10-19 18:07:34] >  composer --ignore-platform-reqs --no-interaction install [/Users/max/magento/vagrant-magento/scripts/host/composer.sh]
[2017-10-19 18:07:35] Initializing vagrant box [init_project.sh]
[2017-10-19 18:07:36] Directory '/Users/max/magento/vagrant-magento/etc' was not mounted as expected by Vagrant.
        Please make sure that 'paliarush/magento2.ubuntu' Vagrant box was downloaded successfully (if not, this may help http://stackoverflow.com/questions/35519389/vagrant-cannot-find-box)
        And that Vagrant is able to mount VirtualBox shared folders on your environment (see https://www.vagrantup.com/docs/synced-folders/basic_usage.html ) [/Users/max/magento/vagrant-magento/scripts/host/check_mounted_directories.sh]
MacBook-Pro-de-Max:vagrant-magento max$ 

I'm using Vagrant 2.0.0 and VirtualBox 5.2.0 on Mac OS X Sierra.

**Comment by paliarush** [comment]
Looks like some NFS issue on your host. I have not tested this on Sierra yet. Make sure that NFS server is running on your host, also take a look at https://github.com/paliarush/magento2-vagrant-for-developers/issues/140

**Comment by shrinet** [comment]
Hello @paliarush I am getting same error on windows 10, earlier it was working fine but yesterday I run again `init_project.sh` since then I am getting the error.
`[2017-12-11 14:47:44] Directory '/e/magento2/vagrant-magento/etc' was not mounted as expected by Vagrant.
        Please make sure that 'paliarush/magento2.ubuntu' Vagrant box was downloaded successfully (if not, this may help http://stackoverflow.com/questions/35519389/vagrant-cannot-find-box)
        And that Vagrant is able to mount VirtualBox shared folders on your environment (see https://www.vagrantup.com/docs/synced-folders/basic_usage.html ) [/e/magento2/vagrant-magento/scripts/host/check_mounted_directories.sh]
`
I am using Vagrant 1.9.1 on windows 10.
Please suggest needful.

**Comment by paliarush** [comment]
@shrinet please see #88 and check if simple vagrant configuration suggested there works for you.

**Comment by shrinet** [comment]
Again I found same issue om mac 10.12.6 vagrant 2.0.1. 
`[2017-12-19 02:23:29] Directory '/Users/shrinet/Documents/dev/magento/magento2-vagrant/etc' was not mounted as expected by Vagrant.
        Please make sure that 'paliarush/magento2.ubuntu' Vagrant box was downloaded successfully (if not, this may help http://stackoverflow.com/questions/35519389/vagrant-cannot-find-box)
        And that Vagrant is able to mount VirtualBox shared folders on your environment (see https://www.vagrantup.com/docs/synced-folders/basic_usage.html ) [/Users/shrinet/Documents/dev/magento/magento2-vagrant/scripts/host/check_mounted_directories.sh]`

Please suggest

**Comment by graemelambert** [comment]
@shrinet if you try to run `vagrant box add paliarush/magento2.ubuntu` you will see the vagrant box will only work on vagrant 1.8.x.

**Comment by al1357** [comment]
I have the same issue on Ubuntu 16.04.3, Vagrant 1.8.7 and VirtualBox 5.0.40. Same error occurs on Vagrant 2.0.1 and VirtualBox 5.2.4.

I was able to successfully run Laravel Homestead on the same computer(vgr 2.0.1 & vb 5.2.4).

**Comment by luukskeur** [comment]
This issue still persists on Windows 10 in combination with Vagrant 1.8.x, Vagrant 2.x and VirtualBox 5.2.

What worked for me was downgrading Vagrant to 1.8.4 (not sure if 1.8.7 is possible too) and VirtualBox to 5.0.40. 
I found the error using the debug option which can be found in this repo's README (the error above is very general). Running only `vagrant up` in the project folder gave the same error so it is a vagrant-specific error. At Vagrant 2.x it explicit says in need to use vagrant v.1.8.x. After downgrading (both vagrant an virtualbox) I ran `rm -rf ~/.vagrant.d` [ found here](https://github.com/hashicorp/vagrant/issues/4918) and after all it is working correctly now. The `bash init_project.sh` is also working as expected after above changes. (running git bash as admin may also help)

**Comment by burhandodhy** [comment]
I have the same issue. Any solution?

**Comment by pouyanafisi** [comment]
For anyone else still having an issue with the install just change the minimum vagrant compatibility check at the top of your `/Vagrantfile` from

`Vagrant.require_version "~> 1.8" ` to `Vagrant.require_version ">= 1.8"`

**Comment by EugeneSuhoviy** [comment]
@pxlhero thanks a lot! Worked for me

**Comment by 9ntonio** [comment]
@pxlhero thanks also. It worked for me as well.

**Comment by ChildHua** [comment]
I have the same issue. Any solution?

**Comment by lhenkel** [comment]
My issue was I haven't used Vagrant in a while and evidently they've moved servers and didn't put redirects.
I added 
Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
to the Vagrantfile and stuff started working.  It was trying to download from atlas before.

**Comment by sreez** [comment]
I am getting similar error from **vagrant-magento/scripts/host/check_mounted_directories.sh** in Windows 10 with Vagrant 2.2.5 and Virtual Box 6. I have another Laravel homestead box which is working fine.

` Directory '/d/dev/vagrant-magento/etc' was not mounted as expected by Vagrant.
        Please make sure that 'paliarush/magento2.ubuntu' Vagrant box was downloaded successfully (if not, this may help http://stackoverflow.com/questions/35519389/vagrant-cannot-find-box)
        And that Vagrant is able to mount VirtualBox shared folders on your environment (see https://www.vagrantup.com/docs/synced-folders/basic_usage.html ).
        Also remove any stale declarations from /etc/exports on the host.`

The file ${vagrant_dir}/etc/guest/mysql/my.cnf is not created. I can see the etc/guest folder with only the .gitignore file in it

UPDATE:
I have found this in the log
`

'error: Vagrant was unable to mount VirtualBox shared folders. This is usually                                                                                                                   because the filesystem "vboxsf" is not available. This filesystem is                                                                                                                                               made available via the VirtualBox Guest Additions and kernel module.                                                                                                                                               Please verify that these guest additions are properly installed in the                                                                                                                                             guest. This is not a bug in Vagrant and is usually caused by a faulty                                                                                                                                              Vagrant box. For context, the command attempted was:                                                                                                                                                                                                                                                                                                                                                                                  mount -t vboxsf -o uid=1000,gid=1000 vagrant_log /vagrant/log
--


`

**Comment by sreez** [comment]
${vagrant_dir}/etc/guest/mysql/my.cnf file is not created
