### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by asimsoroya** [paliarush/vagrant-magento#165]
Hi I am trying to clone from this repo and getting permission error, is it publicly available if yes why im getting the error thanks

**Comment by nfourteen** [comment]
Where are you getting a "permission denied (publickey)" error? If you were trying to clone this repo and got that error, then see [Connecting to Github with SSH](https://help.github.com/articles/connecting-to-github-with-ssh/) and make sure you've added your SSH key to the ssh-agent via `ssh-add`. You can check if it has been added to the agent with `ssh-add -l`.

If you were able to clone this repo and got the error while running the `bash init_project.sh` script, it's because the box is trying to clone the Magento repo, but doesn't have access to the host's SSH keys. Add `config.ssh.forward_agent = true` to the end of the `Vagrantfile`. Or create new SSH keys in the box and set them up in Github.

**Comment by paliarush** [comment]
@nfourteen Thanks for answering the question, added it to the FAQ section for others.
