### ISSUE TITLE
Options missing from design configuration in backend

### ISSUE THREAD

**Issue by aaronallen8455** [paliarush/vagrant-magento#25]
Hi,
I followed the instructions and got the store up and running. The problem I'm having is that the only option showing up in the design configuration area is for 'Search Engine Robots', everything else is missing and so I have no way of changing the theme. Any ideas?
Thanks

**Comment by paliarush** [comment]
Hi @aaronallen8455 . You should follow instructions provided in http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-apply.html . The only difference is that theme configuration was moved to `Content => Design => Configuration` in the latest develop branch. When you check out develop branch you technically get unreleased Magento v2.1 (which has significant changes comparing to v2.0). That's why some flows may be different from those described in the public documentation.
