### ISSUE TITLE
Application very slow, VagrantFile settings, Magento app permissions error

### ISSUE THREAD

**Issue by LCIJJ** [paliarush/vagrant-magento#78]
Per [instructions document](https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/docs/phpstorm-configuration-windows-hosts.md) adding the following code to VagrantFile:

`Vagrant.configure(2) do |config|
  config.vm.synced_folder '../magento2ce/var', '/var/www/magento2ce/var'
  config.vm.synced_folder '../magento2ce/app/etc', '/var/www/magento2ce/app/etc'
end`

...causes this error:
![screen](https://cloud.githubusercontent.com/assets/20110851/17896848/099de66a-6920-11e6-9bc9-4b4513e9fe1c.jpg)
If I take out the code and `vagrant reload` the application runs but has very slow page load times (1-2 minutes).

Why would this code cause a permissions error?

I'm running on Win7, downloaded Magento code via Composer and have EE edition inside "magento2ce" folder.

**Comment by paliarush** [comment]
@LCIJJ Thanks for reporting the issue. Actually that code is already [included in Vagrantfile](https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/Vagrantfile#L59), so no need to modify anything (manual was written before this flow was automated).

Since you have Magento from Composer, I'm not sure what can be wrong with permissions (this flow is not natively supported by current vagrant project), but you can always login to the machine using `vagrant ssh`, and then do `chown vagrant:vagrant` for Magento codebase.
