### ISSUE TITLE
How to connect mysql on windows via Navicat?

### ISSUE THREAD

**Issue by minhluan259** [paliarush/vagrant-magento#8]

**Comment by paliarush** [comment]
As far as I know, all MySQL clients are able to create SSH tunnel, here is dedicated [docs page](https://www.navicat.com/manual/online_manual/en/navicat/rv_manual/SSHSettings.html) for Navicat.

To get ssh credentials, navigate to project root folder (that which contains "Vagrantfile") and execute `vagrant ssh-config`. There you should see HostName (127.0.0.1), Port (custom for your installation), User (vagrant) and IdentityFile (custom path to SSH private key). It should also be possible to use `vagrant` password instead of private key.

**Comment by paliarush** [comment]
@minhluan259 will you be able to contribute PR with corresponding section to the [readme](https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/README.md)? It would help other guys who might have the same question. Just avoid Navicat-specific guidance.

**Comment by minhluan259** [comment]
Thank you. I have connect success with config:
![image](https://cloud.githubusercontent.com/assets/7834473/13718753/8a3338e8-e81f-11e5-8ca8-4cda9a2265dc.png)
![image](https://cloud.githubusercontent.com/assets/7834473/13718759/a72eb74c-e81f-11e5-91d7-1607d4db65f9.png)

Port from config.yam : 3192 (forwarded_ssh_port)
Username/password: vagrant/vagrant

**Comment by refaelgold** [comment]
There is an option to connect to mysql via IDE like phpstorm?

**Comment by paliarush** [comment]
@refaelgold sure, I personally use PhpStorm to connect to DB (via SSH tunnel), see https://confluence.jetbrains.com/display/PhpStorm/Databases+and+SQL+Editor+in+PhpStorm#DatabasesandSQLEditorinPhpStorm-Settingupadatabaseconnection
