### ISSUE TITLE
Add composer parallel install plugin

### ISSUE THREAD

**Issue by hvstudio** [paliarush/vagrant-magento#80]
https://github.com/hirak/prestissimo

**Comment by paliarush** [comment]
@hvstudio thank you for suggestion. Not sure it is possible since one of basic principles in current vagrant project is that source code is managed only on the host machine. It means that even `composer install` is executed on the host. This is necessary for Windows hosts, which have configured one-way code base synchronization (from host to guest), for performance reasons.

I will consider this option for OSX hosts only.

**Comment by paliarush** [comment]
@hvstudio have you tried to measure installation time with and without this plugin? For me it is approximately the same on `composer install` for Magento cloned from git with clean `vendor` directory (8-10 seconds).

Will reopen the issue if there is a scenario for which it make sense to use this plugin.
