### ISSUE TITLE
Cannot install packages using Magento 2.1 Setup Wizard

### ISSUE THREAD

**Issue by aarcro** [paliarush/vagrant-magento#85]
The source directory is exported with uid:gid 501:20, but it should probably be 1000:1000 to match the vagrant user in the VM, correct?

**Comment by paliarush** [comment]
Actually this is how Vagrant mounts NFS folders by default, there are no custom permissions specified in https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/Vagrantfile#L56 . 
I have not noticed any issues with permissions, have you? Basically everything in this box configured to be run by vagrant user and all Magento files are owned by this user.

**Comment by aarcro** [comment]
I was trying to run the web setup wizard, and when it runs its `Readiness Check` the `Check Cron Scripts` set fails, which I thought might be related.

If the updater needs to write anything in the NFS folder it will not be able to.

**Comment by paliarush** [comment]
It should be able because all cron jobs and all php scripts are executed from vagrant user.
It is possible that cron jobs for updater were changed/added recently and thus should be added to the box. 
Does this happens for you with updater only or during initial Magento installation as well?

Update: just checked upgrade flow from CE 2.0.9, `Check Cron Scripts` passed. Which version are you trying to upgrade from?

**Comment by aarcro** [comment]
I'm running 2.1 and just trying to install extensions from the market place.

**Comment by skaragoez** [comment]
I have also the same issue here with 2.1.5. Cron scripts check fails.

**Edit:** I solved the issue with running ```composer install``` at ```<root>/update``` directory.
In my case the command ```/vagrant-magento/magento2ce/update/cron.php```caused an ```/update/vendor/autoload.php): failed to open stream: No such file or directory``` error.

A good way how to debug is to ```crontab -u vagrant -l``` and run the commands one by one.
